<?php

namespace EntasisBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($categoryName)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $category = $qb
            ->select('c')
            ->from('EntasisBundle:Category', 'c')
            ->where('c.ruName LIKE :name OR c.enName LIKE :name')
            ->setParameter('name', $categoryName)
            ->getQuery()
            ->getOneOrNullResult();

        return $category;
    }
}
