<?php

namespace EntasisBundle\Repository;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    const PRODUCTS_ON_PAGE = 8;

    public function findAll()
    {
        return $this->createQueryBuilder('p')
            ->getQuery();
    }

    public function findForUpdate($id)
    {
        $product = $this->getEntityManager()->getRepository('EntasisBundle:Product')
            ->find($id);
        $product->setHiddenImage($product->getTitleImage());
        $product->setHiddenImages($product->getImages());
        $product->setTitleImage(null);
        $product->setImages(null);

        return $product;
    }

    public function findProductsByCategory($categoryName)
    {
        $category = $this->getEntityManager()->getRepository('EntasisBundle:Category')
            ->findByName($categoryName);

        if ($categoryName != null) {
            return $this->createQueryBuilder('p')
                ->where('p.category = :category')
                ->setParameter('category', $category)
                ->getQuery();
        }

        return null;
    }
}
